### ISSUE TITLE
Cannot install spree_shared gem

### ISSUE THREAD

**Issue by nuno84** [spree-contrib/spree_shared#12]
Hello,
I created a new Rails 4.2.1 project and installed ruby 2.1.6p336
I added to gemfile:
gem 'spree_shared', github: 'spree-contrib/spree_shared', branch: 'master'
However, when running bundle -> install I get this error:
Bundler could not find compatible versions for gem "spree_core":

  In Gemfile:
    spree_shared (>= 0) ruby depends on
      spree_core (~> 3.1.0.beta) ruby
Could not find gem 'spree_core (~> 3.1.0.beta) ruby', which is required by gem
'spree_shared (>= 0) ruby', in any of the sources.

I tried to install spree_core, but after the errors, I guess now it is only spree, so I did:
gem install spree
And it seemed to have installed fine.

and tried bundle install again to install spree_shared, but the error persisted.
Can anyone help me?
I want to test the spree_shared and if there is some way to configure the gemfile, even if it means I need to use older version of spree, it would be fine for now.
Thank you,
Nuno

**Comment by JDutil** [comment]
Try using the 3-0-stable branches.

**Comment by nuno84** [comment]
It works.
For other people reference:
gem 'spree_shared', github: 'spree-contrib/spree_shared', branch: '3-0-stable'
Thank you JDutil

**Comment by MarkMT** [comment]
Thanks, I also found this helpful. Nonetheless it appears that master still points at a version of spree_core that does not exist. So it's not clear to me that this issue should be closed.
