### ISSUE TITLE
Adding new stores

### ISSUE THREAD

**Issue by thelinuxlich** [spree-contrib/spree_shared#3]
Everytime I want to add a new store, I will have to edit `config/apartment.rb` and add it to `config.tenant_names`, then restart the Rails app?

**Comment by raulperezalejo** [comment]
you don´t need to restart the server each time you add a new store, just: 

Apartment.configure do |config|
  config.tenant_names = lambda{ User.pluck(:subdomain) }
end

where 'User'  is the model where account are created and 'subdomain' are the name of the stores or any equivalent.

**Comment by JDutil** [comment]
:+1: good solution @raulperezalejo I learned of that after answering this question.
