### ISSUE TITLE
Issue with Sidekiq on Spree 3.0 with spree_shared

### ISSUE THREAD

**Issue by romul** [spree-contrib/spree_shared#9]
In development mode (`config.cache_classes = false`) `bundle exec sidekiq` causes the such error:
```
Cannot define multiple 'included' blocks for a Concern
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/concern.rb:126:in `included'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree-80c47e09d7bc/core/app/models/spree/preferences/preferable.rb:37:in `<module:Preferable>'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/spree-80c47e09d7bc/core/app/models/spree/preferences/preferable.rb:34:in `<top (required)>'
...
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/Users/roman/www/application/config/environment.rb:5:in `<top (required)>'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:236:in `boot_system'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.2/lib/sidekiq/cli.rb:50:in `run'
/Users/roman/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/sidekiq-3.3.2/bin/sidekiq:8:in `<top (required)>'
/Users/roman/.rbenv/versions/2.1.2/bin/sidekiq:23:in `load'
/Users/roman/.rbenv/versions/2.1.2/bin/sidekiq:23:in `<main>'
```
Looks like a double load of some files. I'm pretty sure, that this bug isn't restricted to sidekiq and can appear in other cases.

**Comment by JDutil** [comment]
It may or may not help to try removing the spring gem we've been having all sorts of code reloading issues from it, and removing spring generally solves the problems although not sure if this ones related at all.

**Comment by romul** [comment]
@JDutil No, this one isn't related to spring. It is because of https://github.com/spree-contrib/spree_shared/blob/master/lib/spree_shared/spree_preferences_extensions.rb
But I don't really understand why not https://github.com/spree-contrib/spree_shared/commit/97008d3a029131a23e8376d0b6fdfb442e82dd30
Do you have any insights?

**Comment by romul** [comment]
On the one hand such eager loading can help to override behavior of some initializers (who knows which ones?). But on the second hand, it looks like nonsense, b/c we set Apartment::Tenant.current_tenant from request subdomain, so in all initializers it will be just 'public'.

**Comment by JDutil** [comment]
I'm not really sure this extension was written by someone else, and I've just done some upgrades to it as necessary.  I think your changes look fine, but would be good to test them out.  It looks like the initial code was done back in 2012:
https://github.com/spree-contrib/spree_shared/commit/e1c54018eddc22a2958d0e0fe48b3243dbc8021f

There probably just wasn't as clear of best practices when writing extensions then.

**Comment by romul** [comment]
I've figured out the reason of this strange preloading. That was needed for specs, but the same result can be achieved with help of regular eager loading: https://github.com/spree-contrib/spree_shared/blob/3-0-stable/lib/spree_shared/engine.rb#L10..L12
